Ssh-key aad to ssh-agent
0lmi/devops-training pull request #14
Opened 2023-11-21 17:21 UTC by Lorissxd

Full tutorial is how you can create the ssh-key and add it to your ssh-agent

2023-11-21 17:44 UTC, qwwek commented
А зачем фотка снежного леса в конце?

2023-11-21 17:47 UTC, Lorissxd commented
> А зачем фотка снежного леса в конце?

Ну это для эстетики, там линк на фотку которая каждый раз меняется.

2023-11-24 08:55 UTC, 0lmi requested changes
за исключением некоторых небольших моментов по оформлению текста в MD выглядит хорошо 👍

2023-11-24 08:55 UTC, 0lmi commented on linux/nikita/sshtasks.md
> +ssh-keygen -t ed25519 -C "example@linux.eu"
чаще используется RSA вместо ed25519

какие-то конкретные намерения для использования ed25519 или просто так нашел в используемом туториале?

2023-11-24 08:55 UTC, 0lmi commented on linux/nikita/sshtasks.md
> +> id_ed25519.pub > copy the text inside
обычно `>` символ в начале строки используется для комментирования какой-то части текста где-то уже упомянутого ранее

2023-11-24 08:55 UTC, 0lmi commented on linux/nikita/sshtasks.md
> +** Use root to do it **
если между звездочкой и текстом есть пробелы, то жирным текст подсвечиваться в браузере не будет

2023-11-24 08:55 UTC, 0lmi commented on linux/nikita/sshtasks.md
> +** Note **
такой блок используется для подсвечивания того, что происходит в коде или консоли, Notes надо выделить каким-то другим способом

2023-11-24 08:55 UTC, 0lmi commented on linux/nikita/sshtasks.md
> +All of this steps are provided to make in UNIX based system
в MD формате символ новой строки `/n` не создает новую строку, для этого надо использовать 2 пробела

2023-11-24 09:36 UTC, Lorissxd commented on linux/nikita/sshtasks.md
> +ssh-keygen -t ed25519 -C "example@linux.eu"
Просто я прочитал что ключ ed25519 является более безопасным и чаще всего в форумах его и описывают. 
Поэтому решил переделать.

2023-11-24 09:37 UTC, Lorissxd commented on linux/nikita/sshtasks.md
> +> id_ed25519.pub > copy the text inside
Хорошо переделаю эту строчку

2023-11-26 15:25 UTC, Lorissxd reviewed
Fixed all things, which being required.

2023-11-26 19:12 UTC, 0lmi commented on linux/nikita/sshtasks.md
> +>All of this steps are provided to make in UNIX based system
с какой целью во всем файле используются комментарии (начало строки с `>`)? что именно ты комментируешь?

2023-11-26 23:24 UTC, Destoooooo commented on linux/nikita/sshtasks.md
> +>All of this steps are provided to make in UNIX based system
But

2023-12-18 20:10 UTC, merged