Empty folder explain task
0lmi/devops-training pull request #15
Opened 2023-11-21 18:43 UTC by Lorissxd

Explained the task why did directory in linux still have the size.

2023-11-25 16:11 UTC, 0lmi reviewed
Hint: pay attention that on different file systems empty folder size is different
```
olmi@olmi-vm:/mnt/disk1$ sudo mkdir test_folder
olmi@olmi-vm:/mnt/disk1$ ls -ld test_folder/
drwxr-xr-x 2 root root 2048 nov.  25 17:05 test_folder/
olmi@olmi-vm:/mnt/disk1$ 
olmi@olmi-vm:/mnt/disk1$ cd
olmi@olmi-vm:~$ mkdir test_folder
olmi@olmi-vm:~$ ls -ld test_folder/
drwxrwxr-x 2 olmi olmi 4096 nov.  25 17:06 test_folder/
olmi@olmi-vm:~$
olmi@olmi-vm:~$ df -h / /mnt/disk1/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3        49G   19G   28G  41% /
/dev/loop15      86M   22K   79M   1% /mnt/disk1
```

2023-11-26 19:14 UTC, 0lmi commented on linux/nikita/empty.md
> +>Its only most populars parts of the folder but its enough for now to understand why did empty directory have size
зачем тут комментарий? что ты комментируешь?

2023-11-27 05:29 UTC, Lorissxd reviewed
Cleared every comment parts.

2023-11-27 06:33 UTC, 0lmi commented on linux/nikita/empty.md
> +>Better if you not use the upper letters in name.
почему лучше не использовать заглавные буквы?

2023-11-27 06:34 UTC, 0lmi commented
Пока ответа на основной вопрос "почему пустая папка занимает место на диске" нет.

2024-02-13 10:31 UTC, 0lmi commented on linux/nikita/empty.md
> +#Make an empty directory and check it’s size, explain why does empty directory has size and why is it exactly like this
Название файла (`empty.md`) не такое как должно быть.

2024-02-13 10:31 UTC, 0lmi commented on linux/nikita/empty.md
> +1. (Check disk space usage) it show that folder still have the size 4K, thats mean 4000 bytes `linux not showing the decimal, hundredths, thousandths parts`.
почему 4K = 4000 bytes?

2024-02-13 10:32 UTC, 0lmi commented
Ответа на вопрос по преждему нет.

2024-03-23 12:18 UTC, 0lmi requested changes
Не соответствует базовым правилам.

2024-04-08 19:01 UTC, 0lmi requested changes

2024-04-08 19:01 UTC, 0lmi commented on linux/nikita/READ-ME-empty-folder-aspect
> +The size 4096 bytes, its provided minimal storage in 4 blocks to hold metadata inside of it.
В тексте какая-то каша, предраться можно много к чему, но если даже это все опустить, то ответ полностью неправильный.

2024-04-23 08:46 UTC, 0lmi approved these changes
It's still some questions here and there, but in general it's way better than it ever was, so approving it

2024-04-23 09:22 UTC, merged