TCP connection by using SSH
0lmi/devops-training pull request #17
Opened 2023-11-26 17:32 UTC by Lorissxd

Task is:
Establish TCP connection between 2 Linux hosts and transfer data through it.

2023-11-27 05:42 UTC, Lorissxd reviewed
**Cleared every comment parts**

2023-11-27 06:40 UTC, 0lmi requested changes
Какого уровня модели OSI протокол SSH? Задача передать данные по TCP не используя никакие протоколы более высоких уровней.

2023-11-27 06:40 UTC, 0lmi commented on linux/nikita/tcp.md
> +#Establish TCP connection between 2 Linux hosts and transfer data through it.
Названия MD файлов обычно делают по шаблону `README-<something>.md`

2023-11-27 06:40 UTC, 0lmi commented on linux/nikita/tcp.md
> +For this task i will created 2 virtual machines, which is based on unix system (Kali.Ubuntu)
Are Kali & Ubuntu really Unix system? Если подходить формально, то Linux is not Unix.

2023-11-28 05:21 UTC, Lorissxd reviewed
Made this task by different way to touch only TCP connection

2024-03-23 12:18 UTC, 0lmi requested changes
Не соответствует базовым правилам.

2024-04-08 19:05 UTC, 0lmi requested changes
в целом по заданию хорошо, но в маркдауне ошибки

2024-04-08 19:05 UTC, 0lmi commented on linux/nikita/README-transfer-data-tcp.md
> +#Establish TCP connection between 2 Linux hosts and transfer data through it.
MD: missing space after '#'

2024-04-08 19:05 UTC, 0lmi commented on linux/nikita/README-transfer-data-tcp.md
> +**Host Reciever**
in the visualized markdown it's missing 'new line' before and after this line

2024-04-08 19:05 UTC, 0lmi commented on linux/nikita/README-transfer-data-tcp.md
> +**Host Sender**
the same as the previous comment - missing new lines

2024-04-23 08:48 UTC, 0lmi approved these changes

2024-04-23 09:30 UTC, merged